In [45]:
import numpy as np
import random
from numpy import linalg as la

#1 Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно
a = np.arange(12, 24, 1)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [46]:
#2 Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.
b1 = np.array([list(a[0:1:1]), list(a[6:7:1])] )
b1
b2 = np.array([list(a[0:2:1]), list(a[6:8:1])] )
b2
b3 = np.array([list(a[0:3:1]), list(a[6:9:1])] )
b3
b4 = np.array([list(a[0:4:1]), list(a[6:10:1])] )
b4
b5 = np.array([list(a[0:5:1]), list(a[6:11:1])] )
b5

array([[12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

In [48]:
#2 Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.
c = []
for i in range(1, 6):
    c.append(np.array([list(a[0:i:1]), list(a[6:6+i:1])]))
c

[array([[12],
        [18]]),
 array([[12, 13],
        [18, 19]]),
 array([[12, 13, 14],
        [18, 19, 20]]),
 array([[12, 13, 14, 15],
        [18, 19, 20, 21]]),
 array([[12, 13, 14, 15, 16],
        [18, 19, 20, 21, 22]])]

In [50]:
#3 Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).
c = []
for i in range(1, 6):
    c.append(np.array([list(a[i:i+2:1]), list(a[5+i:7+i:1])]))
c

[array([[13, 14],
        [18, 19]]),
 array([[14, 15],
        [19, 20]]),
 array([[15, 16],
        [20, 21]]),
 array([[16, 17],
        [21, 22]]),
 array([[17, 18],
        [22, 23]])]

In [ ]:
#4 Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
# ДА!

In [67]:
#5Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив
mu = 0
sigma = 1.0
c = []
for i in range(1, 13):
    c.append(random.normalvariate(mu, sigma))


b1 = np.array([list(c[0:4:1]), list(c[4:8:1]), list(c[8:12:1]) ] )


c1=[]
for i in range(len(b1)):
    for j in range (len(b1[i])):
        c1.append(b1[i][j])
        
c1    

[0.40577038911801544,
 -1.2051390643759796,
 -0.2396958812723654,
 -0.262273606616705,
 -1.205822261069534,
 0.7749690784211252,
 -1.8956294852584576,
 -0.44249942205109194,
 -0.6792165820564782,
 0.9602597604339129,
 -1.3319318970386982,
 -0.7301841958932866]

In [66]:
#6Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [69]:
#7Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?
b = np.arange(20, 1, -2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [53]:
#9
d = np.arange(0, 12, 1)
A = np.array([list(d[0:3:1]), list(d[3:6:1]), list(d[6:9:1]),list(d[9:12:1])])
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [56]:
At = A.transpose()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [57]:
B = np.matmul(A, At, out=None)
B
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [50]:
B_inv = la.inv(B)
B_inv
#ОБРАТНАЯ МАТРИЦА НЕ СУЩЕСИТВУЕТ МАТРИЦА СИНГУЛЯРНАЯ



LinAlgError: 1-dimensional array given. Array must be at least two-dimensional

In [87]:
# детерминант равен нулю  обратная матрица не существует
la.det(B)

0.0

In [58]:
#10 Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.
random.seed(42)
random.random()

0.6394267984578837

In [69]:
#Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 
mas=[] 
for i in range(16): 
    mas.append(random.randint(0, 16))

m = np.array(mas)
m

array([13,  7, 14,  8,  0,  5, 13, 10,  8,  4,  6, 10,  3,  2, 12,  3])

In [70]:
sam=[] 
for i in range(16): 
    sam.append([mas])

C= np.array(sam)
C

array([[[13,  7, 14,  8,  0,  5, 13, 10,  8,  4,  6, 10,  3,  2, 12,  3]],

       [[13,  7, 14,  8,  0,  5, 13, 10,  8,  4,  6, 10,  3,  2, 12,  3]],

       [[13,  7, 14,  8,  0,  5, 13, 10,  8,  4,  6, 10,  3,  2, 12,  3]],

       [[13,  7, 14,  8,  0,  5, 13, 10,  8,  4,  6, 10,  3,  2, 12,  3]],

       [[13,  7, 14,  8,  0,  5, 13, 10,  8,  4,  6, 10,  3,  2, 12,  3]],

       [[13,  7, 14,  8,  0,  5, 13, 10,  8,  4,  6, 10,  3,  2, 12,  3]],

       [[13,  7, 14,  8,  0,  5, 13, 10,  8,  4,  6, 10,  3,  2, 12,  3]],

       [[13,  7, 14,  8,  0,  5, 13, 10,  8,  4,  6, 10,  3,  2, 12,  3]],

       [[13,  7, 14,  8,  0,  5, 13, 10,  8,  4,  6, 10,  3,  2, 12,  3]],

       [[13,  7, 14,  8,  0,  5, 13, 10,  8,  4,  6, 10,  3,  2, 12,  3]],

       [[13,  7, 14,  8,  0,  5, 13, 10,  8,  4,  6, 10,  3,  2, 12,  3]],

       [[13,  7, 14,  8,  0,  5, 13, 10,  8,  4,  6, 10,  3,  2, 12,  3]],

       [[13,  7, 14,  8,  0,  5, 13, 10,  8,  4,  6, 10,  3,  2, 12,  3]],

       [[13,

In [71]:
B1 = m*10
B1

array([130,  70, 140,  80,   0,  50, 130, 100,  80,  40,  60, 100,  30,
        20, 120,  30])

In [77]:
D=[]
for i in range(len(C)):
    for j in range (len(C[i])):
        D.append(list(C[i][j] + B1[j]))
D = np.array(D)    
D

array([[143, 137, 144, 138, 130, 135, 143, 140, 138, 134, 136, 140, 133,
        132, 142, 133],
       [143, 137, 144, 138, 130, 135, 143, 140, 138, 134, 136, 140, 133,
        132, 142, 133],
       [143, 137, 144, 138, 130, 135, 143, 140, 138, 134, 136, 140, 133,
        132, 142, 133],
       [143, 137, 144, 138, 130, 135, 143, 140, 138, 134, 136, 140, 133,
        132, 142, 133],
       [143, 137, 144, 138, 130, 135, 143, 140, 138, 134, 136, 140, 133,
        132, 142, 133],
       [143, 137, 144, 138, 130, 135, 143, 140, 138, 134, 136, 140, 133,
        132, 142, 133],
       [143, 137, 144, 138, 130, 135, 143, 140, 138, 134, 136, 140, 133,
        132, 142, 133],
       [143, 137, 144, 138, 130, 135, 143, 140, 138, 134, 136, 140, 133,
        132, 142, 133],
       [143, 137, 144, 138, 130, 135, 143, 140, 138, 134, 136, 140, 133,
        132, 142, 133],
       [143, 137, 144, 138, 130, 135, 143, 140, 138, 134, 136, 140, 133,
        132, 142, 133],
       [143, 137, 144, 138, 13

In [76]:
# детерминант равен нулю  обратная матрица не существует для матрицы D
la.det(D)

0.0